# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'lacledeslan/sourceseer'

steps:
- script: docker pull golang
  displayName: 'Fetch image golang'
- script: docker build . -f linux.dockerfile -t $(imageName) --no-cache --build-arg BUILDNODE=Azure;
  displayName: 'Docker Build'
- script: |
    docker login -u $(dockerUser) -p $(dockerPass)
    docker push $(imageName)
  displayName: 'Push to Docker HUB'
